### ISSUE TITLE
Stream wrapper?

### ISSUE THREAD

**Issue by mnapoli** [mindplay-dk/composer-locator#2]
Hi! I wonder if it would make sense to create a stream wrapper to access files through URIs like `composer://vendor/package/file.json`? Or is it out of the scope of this project? How do you use this project yourself?

**Comment by mindplay-dk** [comment]
I thought about doing something similar, yeah.

Note sure it has to be part of this package - likely it would make more sense for such a package to depend on this package.

At the moment, I use it only in this package, to establish a convention for locating language files:

https://github.com/mindplay-dk/lang

I also use it on a closed-source project to locate SQL migration files, so really just another convention.

I can picture using this anywhere you'd need `include`, `require`, `fopen`, `file_get_contents`, etc. to reach into the file-system of another package - because you can't rely on packages being installed in `vendor`, mainly under test, when the root package is the project and therefore not in the `vendor` folder, but also for packages that use `type` and a Composer installer plugin to customize the installation path...

**Comment by mnapoli** [comment]
👍  thanks for the answer
